# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c29fd12d8dcea366284f41c92e82e6c2341fdb4086351fdaa6654a908e7ac743762f62778a31f7e7d0f42cbf100b006d8d6348a79fe8ffa72349ef64fe5fb95a

test:
  secret_key_base: 7d81b95e6aef07f1701d5badff12b0cb173df98c98b5c1734e6d06e2becc6eb0527ca57efe17a3f2f2fe250ec24eb86e26c2dde0ae963e48b7af65b69d75557f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
